spring:
  application:
    name: joy-payment
  datasource:
    url: jdbc:mysql://mysql2:3306/joy
    password: password
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  kafka:
    client-id: joy-payment
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true
      group-id: joy-payment
    bootstrap-servers: kafka:29092
    listener:
      concurrency: 1
      missing-topics-fatal: true
  security:
    oauth2:
      client:
        registration:
          joy-payment-oidc:
            provider: spring
            client-id: joy-payment
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://payment:8093/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: joy-payment-oidc
          joy-payment-authorization-code:
            provider: spring
            client-id: joy-payment
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://payment:8093/authorized"
            scope: member.money.read
            client-name: joy-payment-authorization-code
        provider:
          spring:
            issuer-uri: http://auth:8080
server:
  port: 8093

client:
  banking:
    url: http://banking:8080
  member:
    url: http://joy-api:8080
  money:
    url: http://money:8080