spring:
  application:
    name: joy-admin
server:
  port: 8087
aes:
  key: "@JYOAIPTER1@JYOAIPTER1@JYOAIPTER"
client:
  joy-api:
    url: http://joy-api:8081
  joy-order:
    url: http://joy-order:8084
  joy-item:
    url: http://joy-item:8085