spring:
  application:
    name: joy-api
  datasource:
    url: jdbc:mysql://mysql2:3306/joy
    password: password
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: redis
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:8083
server:
  port: 8080
kafka:
  clusters:
    bootstrapservers: kafka:29092

