spring:
  application:
    name: joy-api
  datasource:
    url: jdbc:mysql://localhost:3308/joy
    password: password
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth:8081
server:
  port: 8080

logging:
  topic: "joy.logging.out.stdout"
  level:
    org.hibernate : DEBUG