spring:
    application:
        name: joy-ui
    thymeleaf:
        cache: false
server:
    port: 8082
aes:
    key: "@JYOAIPTER1@JYOAIPTER1@JYOAIPTER"
harupay:
    clientId: 01955c05-cf31-7b68-af5d-c892c0847a70
    apiKey: 01955c05-cf32-7680-b477-cff57d520735
client:
    joy-order:
        url: http://joy-order:8084
    joy-item:
        url: http://joy-item:8085
    joy-api:
        url: http://joy-api:8081
    payment:
        url: http://payments:8071