spring:
  application:
    name: joy-money
  datasource:
    url: jdbc:mysql://localhost:3308/joy
    password: password
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  kafka:
    client-id: joy-money
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true
      group-id: joy-money
    bootstrap-servers: localhost:9092
    listener:
      concurrency: 1
      missing-topics-fatal: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth:8081
server:
  port: 8085
kafka:
  topic:
    load-money-request:
      inbox:
        events:
          name: load-money-request.inbox.events
    load-money:
      inbox:
        events:
          name: load-money.inbox.events
    decrease-money:
      inbox:
        events:
          name: decrease-money.inbox.events
logging:
  topic: "joy.logging.out.stdout"