spring:
  application:
    name: joy-order
  datasource:
    url: jdbc:mysql://localhost:3308/joy
    password: password
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth:8081
  kafka:
    bootstrap-servers: localhost:9092
client:
  coupon:
    url: http://localhost:8086
  item:
    url: http://localhost:8085
server:
  port: 8084
